### ISSUE TITLE
ImportError: No module named 'coinmarketcap'

### ISSUE THREAD

**Issue by danindiana** [mrsmn/coinmarketcap-api#19]
I get this error when trying to call coinmarketcap. Despite a seemingly successful install using pip.  

Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinmarketcap import Market
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'coinmarketcap'

(venv)speed@speed-desktop:~/py3project/venv/bin$ pip install coinmarketcap
Requirement already satisfied: coinmarketcap in /home/speed/py3project/venv/lib/python3.4/site-packages
Requirement already satisfied: requests in /home/speed/py3project/venv/lib/python3.4/site-packages (from coinmarketcap)

OS: ubuntu Ubuntu 14.04 trusty
 Kernel: x86_64 Linux 3.13.0-129-generic
 Uptime: 3h 4m
 Packages: 4247
 Shell: bash 4.3.11
 Resolution: 1920x1080
 DE: Gnome 3.9.90
 WM: GNOME Shell
 WM Theme: Adwaita
Radiance [GTK2]
, Radiance [GTK3]
 Icon Theme: elementary-xfce-darker
 Font: Cantarell 11
 CPU: AMD FX-8350 Eight-Core @ 4GHz
 GPU: GeForce GTX 750 Ti
 RAM: 9844MiB / 24011MiB

**Comment by mrsmn** [comment]
Strange, seems to work for me™:

```
root@host ~ # pip3.4 install coinmarketcap --upgrade
Requirement already up-to-date: coinmarketcap in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python3.4/dist-packages (from coinmarketcap)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.4/dist-packages (from requests->coinmarketcap)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.4/dist-packages (from requests->coinmarketcap)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.4/dist-packages (from requests->coinmarketcap)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.4/dist-packages (from requests->coinmarketcap)
root@host ~ # python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinmarketcap import Market
>>> coin = Market()
>>> coin.ticker('bitcoin')
[{'24h_volume_usd': '1966770000.0', 'rank': '1', 'percent_change_24h': '-7.18', 'percent_change_7d': '-11.68', 'last_updated': '1505294969', 'total_supply': '16562387.0', 'percent_change_1h': '0.41', 'market_cap_usd': '65886666101.0', 'symbol': 'BTC', 'name': 'Bitcoin', 'available_supply': '16562387.0', 'id': 'bitcoin', 'price_usd': '3978.09', 'price_btc': '1.0'}]
```
I've just published v.4.0.1, can you try updating?
Cheers.

**Comment by danindiana** [comment]
OK. Here is what I've got. 

pip3.4 install coinmarketcap --upgrade
Collecting coinmarketcap
  Downloading coinmarketcap-4.1.tar.gz
Collecting requests (from coinmarketcap)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 3.1MB/s 
Collecting certifi>=2017.4.17 (from requests->coinmarketcap)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 1.9MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests->coinmarketcap)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 3.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->coinmarketcap)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->coinmarketcap)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Installing collected packages: certifi, urllib3, chardet, idna, requests, coinmarketcap
  Found existing installation: requests 2.13.0
    Uninstalling requests-2.13.0:
      Successfully uninstalled requests-2.13.0
  Found existing installation: coinmarketcap 4.0
    Uninstalling coinmarketcap-4.0:
      Successfully uninstalled coinmarketcap-4.0
  Running setup.py install for coinmarketcap ... done
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 coinmarketcap-4.1 idna-2.6 requests-2.18.4 urllib3-1.22
(venv)speed@speed-desktop:~/py3project/venv/bin$ python
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinmarketcap import Market
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/coinmarketcap/__init__.py", line 10, in <module>
    from .core import Market
  File "/usr/local/lib/python3.4/dist-packages/coinmarketcap/core.py", line 6, in <module>
    import requests_cache
ImportError: No module named 'requests_cache'

**Comment by mrsmn** [comment]
Argh, my bad. I forget to add the ```requests_cache``` dependency in my setup.py. Should be fixed with v.4.1.1 I've just pushed to PyPi.

Sorry for the trouble.

Cheers.

**Comment by danindiana** [comment]
Still getting a requests_cache error as of 6:07 PM. 

(venv)speed@speed-desktop:~/py3project/venv/bin$ python
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinmarketcap import Market
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/coinmarketcap/__init__.py", line 10, in <module>
    from .core import Market
  File "/usr/local/lib/python3.4/dist-packages/coinmarketcap/core.py", line 6, in <module>
    import requests_cache
ImportError: No module named 'requests_cache'
